import type { Dictionary } from "./strings";

/**
 * Messenger settings M3: the messenger's interface in more languages (docs/MESSENGER_SETTINGS_STEP3.md).
 * Written by the developer, not a native speaker: each wants a native speaker's check before
 * customers rely on it. Brazilian Portuguese differs from European Portuguese only where usage
 * does; everything else is shared.
 */
const fr: Dictionary = {
  unread: "Non lu",
  support: "assistance",
  spaces: "Espaces de la messagerie",
  poweredBy: "Propulsé par",
  openState: "Ouverte",
  snoozedState: "En pause",
  closedState: "Fermée",
  alertsGranted: "Alertes activées",
  alertsDenied: "Alertes bloquées par votre navigateur",
  alertsDefault: "Les alertes sont désactivées",
  alertsUnsupported: "Ce navigateur ne prend pas en charge les alertes",
  home: "Accueil",
  messages: "Messages",
  help: "Aide",
  close: "Fermer l'assistance",
  start: "Démarrer une conversation",
  welcome: "Comment pouvons-nous vous aider ?",
  recent: "Conversations récentes",
  empty: "Vos conversations apparaîtront ici.",
  write: "Écrivez votre message",
  send: "Envoyer le message",
  back: "Retour aux messages",
  you: "Vous",
  teammate: "Membre de l'équipe",
  ai: "Agent IA",
  sources: "Sources",
  automation: "Automatisation",
  joined: "Un membre de l'équipe a rejoint la conversation",
  closed: "Conversation fermée",
  reopened: "Conversation ouverte",
  merged: "Historiques de conversation fusionnés",
  ticket: "Ticket",
  yourTickets: "Vos tickets et demandes",
  replyFewMinutes: "Nous répondons généralement en quelques minutes",
  replyUnderHour: "Nous répondons généralement en moins d'une heure",
  replyFewHours: "Nous répondons généralement en quelques heures",
  replyDay: "Nous répondons généralement en un jour environ",
  replyFrom: "Nous répondrons à partir de",
  queue: "Position dans la file : {n}",
  portalTitle: "Vos demandes",
  portalEmpty: "Vous n'avez encore aucune demande.",
  portalSignIn:
    "Connectez-vous via notre site ou notre messagerie pour voir vos demandes.",
  portalSignOut: "Se déconnecter",
  portalHelpCenter: "Centre d'aide",
  portalBack: "Toutes les demandes",
  portalReply: "Écrire une réponse",
  portalSend: "Envoyer la réponse",
  portalUpdated: "Mis à jour",
  deleted: "Ce message a été supprimé",
  typing: "Quelqu'un écrit…",
  connecting: "Connexion…",
  connected: "Connecté",
  disconnected: "Reconnexion…",
  unavailable:
    "Les articles d'aide ne sont pas encore disponibles pour cet espace.",
  searchHelp: "Rechercher de l'aide",
  searchButton: "Rechercher",
  noHelpResults:
    "Aucun article ne correspond. Essayez d'autres mots ou démarrez une conversation.",
  helpBack: "Retour",
  helpfulQuestion: "Cet article vous a-t-il aidé ?",
  yes: "Oui",
  no: "Non",
  feedbackThanks: "Merci de nous l'avoir dit.",
  feedbackTellUs: "Que cherchiez-vous ? (facultatif)",
  feedbackSend: "Envoyer",
  talkToUs: "Nous contacter",
  helpSignIn: "Connectez-vous pour voir les articles d'aide.",
  error: "Une erreur s'est produite. Veuillez réessayer.",
  retry: "Renvoyer le message",
  sound: "Jouer un son pour les réponses",
  settings: "Préférences",
  signIn: "Connectez-vous pour démarrer une conversation.",
  upload: "Joindre un fichier",
  scanning: "Vérification de votre fichier…",
  uploadFailed: "Le fichier n'a pas pu être partagé.",
  download: "Télécharger le fichier",
  notifications: "Alertes de réponse du navigateur",
  away: "Nous sommes absents. Laissez un message et nous vous répondrons à notre retour.",
  open: "L'équipe est en ligne pendant les heures d'ouverture.",
  session: "Veuillez vous reconnecter pour continuer.",
  waiting: "Connexion à l'assistance…",
  edited: "Modifié",
  searchFirst:
    "Veuillez chercher dans l'Aide avant de démarrer une conversation.",
  startSend: "Envoyez-nous un message",
  startAsk: "Poser une question",
  startChat: "Discuter avec nous",
  startStart: "Démarrer une conversation",
  startContact: "Nous contacter",
  startSupport: "Contacter l'assistance",
  tickets: "Tickets",
  notice: "Avis",
  team: "L'équipe",
  continueConversation: "Reprendre votre conversation",
  closedNoReply:
    "Cette conversation est fermée. Démarrez-en une nouvelle si vous avez encore besoin d'aide.",
  privacyLink: "Politique de confidentialité",
};

const es: Dictionary = {
  unread: "No leído",
  support: "soporte",
  spaces: "Espacios del messenger",
  poweredBy: "Con la tecnología de",
  openState: "Abierta",
  snoozedState: "Pospuesta",
  closedState: "Cerrada",
  alertsGranted: "Alertas activadas",
  alertsDenied: "Tu navegador bloquea las alertas",
  alertsDefault: "Las alertas están desactivadas",
  alertsUnsupported: "Este navegador no admite alertas",
  home: "Inicio",
  messages: "Mensajes",
  help: "Ayuda",
  close: "Cerrar soporte",
  start: "Iniciar una conversación",
  welcome: "¿En qué podemos ayudarte?",
  recent: "Conversaciones recientes",
  empty: "Tus conversaciones aparecerán aquí.",
  write: "Escribe tu mensaje",
  send: "Enviar mensaje",
  back: "Volver a los mensajes",
  you: "Tú",
  teammate: "Miembro del equipo",
  ai: "Agente de IA",
  sources: "Fuentes",
  automation: "Automatización",
  joined: "Un miembro del equipo se unió a la conversación",
  closed: "Conversación cerrada",
  reopened: "Conversación abierta",
  merged: "Historiales de conversación combinados",
  ticket: "Ticket",
  yourTickets: "Tus tickets y solicitudes",
  replyFewMinutes: "Solemos responder en unos minutos",
  replyUnderHour: "Solemos responder en menos de una hora",
  replyFewHours: "Solemos responder en unas horas",
  replyDay: "Solemos responder en un día aproximadamente",
  replyFrom: "Responderemos a partir de",
  queue: "Posición en la cola: {n}",
  portalTitle: "Tus solicitudes",
  portalEmpty: "Todavía no tienes solicitudes.",
  portalSignIn:
    "Inicia sesión desde nuestro sitio web o messenger para ver tus solicitudes.",
  portalSignOut: "Cerrar sesión",
  portalHelpCenter: "Centro de ayuda",
  portalBack: "Todas las solicitudes",
  portalReply: "Escribe una respuesta",
  portalSend: "Enviar respuesta",
  portalUpdated: "Actualizado",
  deleted: "Este mensaje se eliminó",
  typing: "Alguien está escribiendo…",
  connecting: "Conectando…",
  connected: "Conectado",
  disconnected: "Reconectando…",
  unavailable:
    "Los artículos de ayuda aún no están disponibles para este espacio.",
  searchHelp: "Buscar ayuda",
  searchButton: "Buscar",
  noHelpResults:
    "Ningún artículo coincide. Prueba con otras palabras o inicia una conversación.",
  helpBack: "Volver",
  helpfulQuestion: "¿Te resultó útil?",
  yes: "Sí",
  no: "No",
  feedbackThanks: "Gracias por avisarnos.",
  feedbackTellUs: "¿Qué estabas buscando? (opcional)",
  feedbackSend: "Enviar",
  talkToUs: "Habla con nosotros",
  helpSignIn: "Inicia sesión para ver los artículos de ayuda.",
  error: "Algo salió mal. Inténtalo de nuevo.",
  retry: "Reintentar mensaje",
  sound: "Reproducir un sonido con las respuestas",
  settings: "Preferencias",
  signIn: "Inicia sesión para iniciar una conversación.",
  upload: "Adjuntar un archivo",
  scanning: "Comprobando tu archivo…",
  uploadFailed: "No se pudo compartir el archivo.",
  download: "Descargar archivo",
  notifications: "Alertas de respuesta del navegador",
  away: "No estamos disponibles. Deja un mensaje y te responderemos a nuestro regreso.",
  open: "El equipo está en línea en horario de atención.",
  session: "Vuelve a iniciar sesión para continuar.",
  waiting: "Conectando con soporte…",
  edited: "Editado",
  searchFirst: "Busca en Ayuda antes de iniciar una conversación.",
  startSend: "Envíanos un mensaje",
  startAsk: "Haz una pregunta",
  startChat: "Chatea con nosotros",
  startStart: "Iniciar una conversación",
  startContact: "Contáctanos",
  startSupport: "Contactar con soporte",
  tickets: "Tickets",
  notice: "Aviso",
  team: "El equipo",
  continueConversation: "Continúa tu conversación",
  closedNoReply:
    "Esta conversación está cerrada. Inicia una nueva si necesitas más ayuda.",
  privacyLink: "Política de privacidad",
};

const de: Dictionary = {
  unread: "Ungelesen",
  support: "Support",
  spaces: "Bereiche des Messengers",
  poweredBy: "Bereitgestellt von",
  openState: "Offen",
  snoozedState: "Zurückgestellt",
  closedState: "Geschlossen",
  alertsGranted: "Benachrichtigungen aktiviert",
  alertsDenied: "Benachrichtigungen vom Browser blockiert",
  alertsDefault: "Benachrichtigungen sind aus",
  alertsUnsupported: "Dieser Browser unterstützt keine Benachrichtigungen",
  home: "Start",
  messages: "Nachrichten",
  help: "Hilfe",
  close: "Support schließen",
  start: "Unterhaltung beginnen",
  welcome: "Wie können wir helfen?",
  recent: "Letzte Unterhaltungen",
  empty: "Ihre Unterhaltungen erscheinen hier.",
  write: "Nachricht schreiben",
  send: "Nachricht senden",
  back: "Zurück zu den Nachrichten",
  you: "Sie",
  teammate: "Teammitglied",
  ai: "KI-Agent",
  sources: "Quellen",
  automation: "Automatisierung",
  joined: "Ein Teammitglied ist der Unterhaltung beigetreten",
  closed: "Unterhaltung geschlossen",
  reopened: "Unterhaltung geöffnet",
  merged: "Unterhaltungsverläufe zusammengeführt",
  ticket: "Ticket",
  yourTickets: "Ihre Tickets und Anfragen",
  replyFewMinutes: "Wir antworten normalerweise in wenigen Minuten",
  replyUnderHour: "Wir antworten normalerweise in unter einer Stunde",
  replyFewHours: "Wir antworten normalerweise in wenigen Stunden",
  replyDay: "Wir antworten normalerweise in etwa einem Tag",
  replyFrom: "Wir antworten ab",
  queue: "Ihre Position in der Warteschlange: {n}",
  portalTitle: "Ihre Anfragen",
  portalEmpty: "Sie haben noch keine Anfragen.",
  portalSignIn:
    "Melden Sie sich über unsere Website oder den Messenger an, um Ihre Anfragen zu sehen.",
  portalSignOut: "Abmelden",
  portalHelpCenter: "Hilfecenter",
  portalBack: "Alle Anfragen",
  portalReply: "Antwort schreiben",
  portalSend: "Antwort senden",
  portalUpdated: "Aktualisiert",
  deleted: "Diese Nachricht wurde gelöscht",
  typing: "Jemand schreibt…",
  connecting: "Verbinden…",
  connected: "Verbunden",
  disconnected: "Neu verbinden…",
  unavailable:
    "Hilfeartikel sind für diesen Arbeitsbereich noch nicht verfügbar.",
  searchHelp: "Hilfe durchsuchen",
  searchButton: "Suchen",
  noHelpResults:
    "Keine Artikel gefunden. Versuchen Sie andere Wörter oder beginnen Sie eine Unterhaltung.",
  helpBack: "Zurück",
  helpfulQuestion: "War das hilfreich?",
  yes: "Ja",
  no: "Nein",
  feedbackThanks: "Danke für Ihre Rückmeldung.",
  feedbackTellUs: "Wonach haben Sie gesucht? (optional)",
  feedbackSend: "Senden",
  talkToUs: "Mit uns sprechen",
  helpSignIn: "Melden Sie sich an, um Hilfeartikel zu sehen.",
  error: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
  retry: "Nachricht erneut senden",
  sound: "Ton bei Antworten abspielen",
  settings: "Einstellungen",
  signIn: "Melden Sie sich an, um eine Unterhaltung zu beginnen.",
  upload: "Datei anhängen",
  scanning: "Ihre Datei wird geprüft…",
  uploadFailed: "Die Datei konnte nicht geteilt werden.",
  download: "Datei herunterladen",
  notifications: "Browser-Benachrichtigungen für Antworten",
  away: "Wir sind gerade nicht da. Hinterlassen Sie eine Nachricht, wir antworten, sobald wir zurück sind.",
  open: "Das Team ist während der Geschäftszeiten online.",
  session: "Bitte melden Sie sich erneut an, um fortzufahren.",
  waiting: "Verbindung zum Support…",
  edited: "Bearbeitet",
  searchFirst:
    "Bitte durchsuchen Sie zuerst die Hilfe, bevor Sie eine Unterhaltung beginnen.",
  startSend: "Schreiben Sie uns",
  startAsk: "Frage stellen",
  startChat: "Mit uns chatten",
  startStart: "Unterhaltung beginnen",
  startContact: "Kontakt aufnehmen",
  startSupport: "Support kontaktieren",
  tickets: "Tickets",
  notice: "Hinweis",
  team: "Das Team",
  continueConversation: "Unterhaltung fortsetzen",
  closedNoReply:
    "Diese Unterhaltung ist geschlossen. Beginnen Sie eine neue, wenn Sie weitere Hilfe brauchen.",
  privacyLink: "Datenschutzerklärung",
};

const pt: Dictionary = {
  unread: "Não lida",
  support: "apoio",
  spaces: "Espaços do messenger",
  poweredBy: "Com tecnologia de",
  openState: "Aberta",
  snoozedState: "Adiada",
  closedState: "Fechada",
  alertsGranted: "Alertas ativados",
  alertsDenied: "Alertas bloqueados pelo navegador",
  alertsDefault: "Os alertas estão desligados",
  alertsUnsupported: "Este navegador não suporta alertas",
  home: "Início",
  messages: "Mensagens",
  help: "Ajuda",
  close: "Fechar apoio",
  start: "Iniciar uma conversa",
  welcome: "Como podemos ajudar?",
  recent: "Conversas recentes",
  empty: "As suas conversas aparecerão aqui.",
  write: "Escreva a sua mensagem",
  send: "Enviar mensagem",
  back: "Voltar às mensagens",
  you: "Você",
  teammate: "Membro da equipa",
  ai: "Agente de IA",
  sources: "Fontes",
  automation: "Automatização",
  joined: "Um membro da equipa juntou-se à conversa",
  closed: "Conversa fechada",
  reopened: "Conversa aberta",
  merged: "Históricos de conversa juntos",
  ticket: "Pedido",
  yourTickets: "Os seus pedidos",
  replyFewMinutes: "Normalmente respondemos em poucos minutos",
  replyUnderHour: "Normalmente respondemos em menos de uma hora",
  replyFewHours: "Normalmente respondemos em poucas horas",
  replyDay: "Normalmente respondemos em cerca de um dia",
  replyFrom: "Responderemos a partir de",
  queue: "Posição na fila: {n}",
  portalTitle: "Os seus pedidos",
  portalEmpty: "Ainda não tem pedidos.",
  portalSignIn:
    "Inicie sessão no nosso site ou messenger para ver os seus pedidos.",
  portalSignOut: "Terminar sessão",
  portalHelpCenter: "Centro de ajuda",
  portalBack: "Todos os pedidos",
  portalReply: "Escreva uma resposta",
  portalSend: "Enviar resposta",
  portalUpdated: "Atualizado",
  deleted: "Esta mensagem foi eliminada",
  typing: "Alguém está a escrever…",
  connecting: "A ligar…",
  connected: "Ligado",
  disconnected: "A voltar a ligar…",
  unavailable:
    "Os artigos de ajuda ainda não estão disponíveis para este espaço.",
  searchHelp: "Pesquisar ajuda",
  searchButton: "Pesquisar",
  noHelpResults:
    "Nenhum artigo corresponde. Experimente outras palavras ou inicie uma conversa.",
  helpBack: "Voltar",
  helpfulQuestion: "Isto foi útil?",
  yes: "Sim",
  no: "Não",
  feedbackThanks: "Obrigado por nos dizer.",
  feedbackTellUs: "O que procurava? (opcional)",
  feedbackSend: "Enviar",
  talkToUs: "Fale connosco",
  helpSignIn: "Inicie sessão para ver os artigos de ajuda.",
  error: "Algo correu mal. Tente novamente.",
  retry: "Tentar enviar de novo",
  sound: "Tocar um som nas respostas",
  settings: "Preferências",
  signIn: "Inicie sessão para iniciar uma conversa.",
  upload: "Anexar um ficheiro",
  scanning: "A verificar o seu ficheiro…",
  uploadFailed: "Não foi possível partilhar o ficheiro.",
  download: "Transferir ficheiro",
  notifications: "Alertas de resposta do navegador",
  away: "Estamos ausentes. Deixe uma mensagem e responderemos quando voltarmos.",
  open: "A equipa está online durante o horário de atendimento.",
  session: "Inicie sessão novamente para continuar.",
  waiting: "A ligar ao apoio…",
  edited: "Editado",
  searchFirst: "Pesquise na Ajuda antes de iniciar uma conversa.",
  startSend: "Envie-nos uma mensagem",
  startAsk: "Faça uma pergunta",
  startChat: "Converse connosco",
  startStart: "Iniciar uma conversa",
  startContact: "Contacte-nos",
  startSupport: "Contactar o apoio",
  tickets: "Pedidos",
  notice: "Aviso",
  team: "A equipa",
  continueConversation: "Continuar a sua conversa",
  closedNoReply:
    "Esta conversa está fechada. Inicie uma nova se precisar de mais ajuda.",
  privacyLink: "Política de privacidade",
};

/** Brazilian Portuguese: European Portuguese with Brazil's usage where it differs. */
const ptBR: Dictionary = {
  ...pt,
  support: "suporte",
  teammate: "Membro da equipe",
  joined: "Um membro da equipe entrou na conversa",
  merged: "Históricos de conversa unidos",
  ticket: "Ticket",
  yourTickets: "Seus tickets e solicitações",
  close: "Fechar suporte",
  empty: "Suas conversas aparecerão aqui.",
  write: "Escreva sua mensagem",
  portalTitle: "Suas solicitações",
  portalEmpty: "Você ainda não tem solicitações.",
  portalSignIn:
    "Entre pelo nosso site ou messenger para ver suas solicitações.",
  portalSignOut: "Sair",
  portalBack: "Todas as solicitações",
  deleted: "Esta mensagem foi excluída",
  typing: "Alguém está digitando…",
  connecting: "Conectando…",
  connected: "Conectado",
  disconnected: "Reconectando…",
  feedbackThanks: "Obrigado por nos avisar.",
  feedbackTellUs: "O que você estava procurando? (opcional)",
  talkToUs: "Fale com a gente",
  helpSignIn: "Entre para ver os artigos de ajuda.",
  error: "Algo deu errado. Tente novamente.",
  signIn: "Entre para iniciar uma conversa.",
  upload: "Anexar um arquivo",
  scanning: "Verificando seu arquivo…",
  uploadFailed: "Não foi possível compartilhar o arquivo.",
  download: "Baixar arquivo",
  open: "A equipe está online durante o horário de atendimento.",
  session: "Entre novamente para continuar.",
  waiting: "Conectando ao suporte…",
  startChat: "Converse com a gente",
  startContact: "Fale conosco",
  startSupport: "Falar com o suporte",
  tickets: "Tickets",
  team: "A equipe",
  continueConversation: "Continuar sua conversa",
};

const it: Dictionary = {
  unread: "Non letto",
  support: "assistenza",
  spaces: "Spazi del messenger",
  poweredBy: "Con tecnologia di",
  openState: "Aperta",
  snoozedState: "Posticipata",
  closedState: "Chiusa",
  alertsGranted: "Avvisi attivati",
  alertsDenied: "Avvisi bloccati dal browser",
  alertsDefault: "Gli avvisi sono disattivati",
  alertsUnsupported: "Questo browser non supporta gli avvisi",
  home: "Home",
  messages: "Messaggi",
  help: "Aiuto",
  close: "Chiudi assistenza",
  start: "Inizia una conversazione",
  welcome: "Come possiamo aiutarti?",
  recent: "Conversazioni recenti",
  empty: "Le tue conversazioni appariranno qui.",
  write: "Scrivi il tuo messaggio",
  send: "Invia messaggio",
  back: "Torna ai messaggi",
  you: "Tu",
  teammate: "Membro del team",
  ai: "Agente IA",
  sources: "Fonti",
  automation: "Automazione",
  joined: "Un membro del team si è unito alla conversazione",
  closed: "Conversazione chiusa",
  reopened: "Conversazione aperta",
  merged: "Cronologie delle conversazioni unite",
  ticket: "Ticket",
  yourTickets: "I tuoi ticket e le tue richieste",
  replyFewMinutes: "Di solito rispondiamo in pochi minuti",
  replyUnderHour: "Di solito rispondiamo in meno di un'ora",
  replyFewHours: "Di solito rispondiamo in poche ore",
  replyDay: "Di solito rispondiamo in circa un giorno",
  replyFrom: "Risponderemo a partire da",
  queue: "Posizione in coda: {n}",
  portalTitle: "Le tue richieste",
  portalEmpty: "Non hai ancora richieste.",
  portalSignIn:
    "Accedi dal nostro sito o dal messenger per vedere le tue richieste.",
  portalSignOut: "Esci",
  portalHelpCenter: "Centro assistenza",
  portalBack: "Tutte le richieste",
  portalReply: "Scrivi una risposta",
  portalSend: "Invia risposta",
  portalUpdated: "Aggiornato",
  deleted: "Questo messaggio è stato eliminato",
  typing: "Qualcuno sta scrivendo…",
  connecting: "Connessione…",
  connected: "Connesso",
  disconnected: "Riconnessione…",
  unavailable:
    "Gli articoli di aiuto non sono ancora disponibili per questo spazio.",
  searchHelp: "Cerca aiuto",
  searchButton: "Cerca",
  noHelpResults:
    "Nessun articolo corrisponde. Prova altre parole o inizia una conversazione.",
  helpBack: "Indietro",
  helpfulQuestion: "Ti è stato utile?",
  yes: "Sì",
  no: "No",
  feedbackThanks: "Grazie per avercelo detto.",
  feedbackTellUs: "Cosa stavi cercando? (facoltativo)",
  feedbackSend: "Invia",
  talkToUs: "Parla con noi",
  helpSignIn: "Accedi per vedere gli articoli di aiuto.",
  error: "Qualcosa è andato storto. Riprova.",
  retry: "Riprova a inviare",
  sound: "Riproduci un suono per le risposte",
  settings: "Preferenze",
  signIn: "Accedi per iniziare una conversazione.",
  upload: "Allega un file",
  scanning: "Controllo del file…",
  uploadFailed: "Impossibile condividere il file.",
  download: "Scarica il file",
  notifications: "Avvisi di risposta del browser",
  away: "Non siamo disponibili. Lascia un messaggio e ti risponderemo al nostro ritorno.",
  open: "Il team è online durante l'orario di apertura.",
  session: "Accedi di nuovo per continuare.",
  waiting: "Connessione all'assistenza…",
  edited: "Modificato",
  searchFirst: "Cerca nell'Aiuto prima di iniziare una conversazione.",
  startSend: "Inviaci un messaggio",
  startAsk: "Fai una domanda",
  startChat: "Chatta con noi",
  startStart: "Inizia una conversazione",
  startContact: "Contattaci",
  startSupport: "Contatta l'assistenza",
  tickets: "Ticket",
  notice: "Avviso",
  team: "Il team",
  continueConversation: "Continua la tua conversazione",
  closedNoReply:
    "Questa conversazione è chiusa. Iniziane una nuova se hai bisogno di altro aiuto.",
  privacyLink: "Informativa sulla privacy",
};

const nl: Dictionary = {
  unread: "Ongelezen",
  support: "support",
  spaces: "Onderdelen van de messenger",
  poweredBy: "Mogelijk gemaakt door",
  openState: "Open",
  snoozedState: "Uitgesteld",
  closedState: "Gesloten",
  alertsGranted: "Meldingen aan",
  alertsDenied: "Meldingen geblokkeerd door je browser",
  alertsDefault: "Meldingen staan uit",
  alertsUnsupported: "Deze browser ondersteunt geen meldingen",
  home: "Start",
  messages: "Berichten",
  help: "Hulp",
  close: "Support sluiten",
  start: "Gesprek starten",
  welcome: "Hoe kunnen we helpen?",
  recent: "Recente gesprekken",
  empty: "Je gesprekken verschijnen hier.",
  write: "Schrijf je bericht",
  send: "Bericht versturen",
  back: "Terug naar berichten",
  you: "Jij",
  teammate: "Teamlid",
  ai: "AI-agent",
  sources: "Bronnen",
  automation: "Automatisering",
  joined: "Een teamlid is bij het gesprek gekomen",
  closed: "Gesprek gesloten",
  reopened: "Gesprek geopend",
  merged: "Gespreksgeschiedenis samengevoegd",
  ticket: "Ticket",
  yourTickets: "Je tickets en aanvragen",
  replyFewMinutes: "We reageren meestal binnen een paar minuten",
  replyUnderHour: "We reageren meestal binnen een uur",
  replyFewHours: "We reageren meestal binnen een paar uur",
  replyDay: "We reageren meestal binnen ongeveer een dag",
  replyFrom: "We reageren vanaf",
  queue: "Je plek in de wachtrij: {n}",
  portalTitle: "Je aanvragen",
  portalEmpty: "Je hebt nog geen aanvragen.",
  portalSignIn: "Log in via onze website of messenger om je aanvragen te zien.",
  portalSignOut: "Uitloggen",
  portalHelpCenter: "Helpcentrum",
  portalBack: "Alle aanvragen",
  portalReply: "Schrijf een antwoord",
  portalSend: "Antwoord versturen",
  portalUpdated: "Bijgewerkt",
  deleted: "Dit bericht is verwijderd",
  typing: "Iemand is aan het typen…",
  connecting: "Verbinden…",
  connected: "Verbonden",
  disconnected: "Opnieuw verbinden…",
  unavailable: "Hulpartikelen zijn nog niet beschikbaar voor deze werkruimte.",
  searchHelp: "Hulp zoeken",
  searchButton: "Zoeken",
  noHelpResults:
    "Geen artikelen gevonden. Probeer andere woorden of start een gesprek.",
  helpBack: "Terug",
  helpfulQuestion: "Was dit nuttig?",
  yes: "Ja",
  no: "Nee",
  feedbackThanks: "Bedankt voor je reactie.",
  feedbackTellUs: "Waar was je naar op zoek? (optioneel)",
  feedbackSend: "Versturen",
  talkToUs: "Praat met ons",
  helpSignIn: "Log in om hulpartikelen te zien.",
  error: "Er ging iets mis. Probeer het opnieuw.",
  retry: "Bericht opnieuw versturen",
  sound: "Geluid afspelen bij antwoorden",
  settings: "Voorkeuren",
  signIn: "Log in om een gesprek te starten.",
  upload: "Bestand bijvoegen",
  scanning: "Je bestand wordt gecontroleerd…",
  uploadFailed: "Het bestand kon niet worden gedeeld.",
  download: "Bestand downloaden",
  notifications: "Browsermeldingen bij antwoorden",
  away: "We zijn er even niet. Laat een bericht achter, dan reageren we zodra we terug zijn.",
  open: "Het team is online tijdens de openingstijden.",
  session: "Log opnieuw in om verder te gaan.",
  waiting: "Verbinden met support…",
  edited: "Bewerkt",
  searchFirst: "Zoek eerst in Hulp voordat je een gesprek start.",
  startSend: "Stuur ons een bericht",
  startAsk: "Stel een vraag",
  startChat: "Chat met ons",
  startStart: "Gesprek starten",
  startContact: "Neem contact op",
  startSupport: "Neem contact op met support",
  tickets: "Tickets",
  notice: "Mededeling",
  team: "Het team",
  continueConversation: "Ga verder met je gesprek",
  closedNoReply:
    "Dit gesprek is gesloten. Start een nieuw gesprek als je meer hulp nodig hebt.",
  privacyLink: "Privacybeleid",
};

export const more: Record<string, Dictionary> = {
  fr,
  es,
  de,
  pt,
  "pt-BR": ptBR,
  it,
  nl,
};
