const en = {
  unread: "Unread",
  support: "support",
  spaces: "Messenger spaces",
  poweredBy: "Powered by",
  openState: "Open",
  snoozedState: "Snoozed",
  closedState: "Closed",
  alertsGranted: "Alerts enabled",
  alertsDenied: "Alerts blocked by your browser",
  alertsDefault: "Alerts are off",
  alertsUnsupported: "This browser does not support alerts",
  home: "Home",
  messages: "Messages",
  help: "Help",
  close: "Close support",
  start: "Start a conversation",
  welcome: "How can we help?",
  recent: "Recent conversations",
  empty: "Your conversations will appear here.",
  write: "Write your message",
  send: "Send message",
  back: "Back to messages",
  you: "You",
  teammate: "Support teammate",
  ai: "AI agent",
  automation: "Automation",
  joined: "A teammate joined the conversation",
  closed: "Conversation closed",
  reopened: "Conversation opened",
  merged: "Conversation timelines merged",
  deleted: "This message was deleted",
  typing: "Someone is typing…",
  connecting: "Connecting…",
  connected: "Connected",
  disconnected: "Reconnecting…",
  unavailable: "Help articles are not available for this workspace yet.",
  error: "Something went wrong. Please try again.",
  retry: "Retry message",
  sound: "Play a sound for replies",
  settings: "Preferences",
  signIn: "Sign in to start a conversation.",
  upload: "Attach a file",
  scanning: "Checking your file…",
  uploadFailed: "File could not be shared.",
  download: "Download file",
  notifications: "Browser reply alerts",
  away: "We are away. Leave a message and we will reply when we return.",
  open: "The team is online during office hours.",
  session: "Please sign in again to continue.",
  waiting: "Connecting to support…",
  edited: "Edited",
  searchFirst: "Please search Help before starting a conversation.",
};
const ar: typeof en = {
  unread: "غير مقروءة",
  support: "الدعم",
  spaces: "أقسام المراسلة",
  poweredBy: "بدعم من",
  openState: "مفتوحة",
  snoozedState: "مؤجلة",
  closedState: "مغلقة",
  alertsGranted: "التنبيهات مفعّلة",
  alertsDenied: "المتصفح يحظر التنبيهات",
  alertsDefault: "التنبيهات متوقفة",
  alertsUnsupported: "المتصفح لا يدعم التنبيهات",
  home: "الرئيسية",
  messages: "الرسائل",
  help: "المساعدة",
  close: "إغلاق الدعم",
  start: "بدء محادثة",
  welcome: "كيف يمكننا مساعدتك؟",
  recent: "المحادثات الأخيرة",
  empty: "ستظهر محادثاتك هنا.",
  write: "اكتب رسالتك",
  send: "إرسال الرسالة",
  back: "العودة إلى الرسائل",
  you: "أنت",
  teammate: "فريق الدعم",
  ai: "وكيل الذكاء الاصطناعي",
  automation: "النظام الآلي",
  joined: "انضم أحد أعضاء الفريق إلى المحادثة",
  closed: "أُغلقت المحادثة",
  reopened: "فُتحت المحادثة",
  merged: "دُمجت المحادثات",
  deleted: "حُذفت هذه الرسالة",
  typing: "يكتب شخص ما…",
  connecting: "جارٍ الاتصال…",
  connected: "متصل",
  disconnected: "جارٍ إعادة الاتصال…",
  unavailable: "مقالات المساعدة غير متاحة بعد.",
  error: "حدث خطأ. يرجى المحاولة مجدداً.",
  retry: "إعادة إرسال الرسالة",
  sound: "تشغيل صوت للردود",
  settings: "التفضيلات",
  signIn: "سجّل الدخول لبدء محادثة.",
  upload: "إرفاق ملف",
  scanning: "جارٍ فحص الملف…",
  uploadFailed: "تعذرت مشاركة الملف.",
  download: "تنزيل الملف",
  notifications: "تنبيهات المتصفح للردود",
  away: "نحن غير متاحين حالياً. اترك رسالة وسنرد عند عودتنا.",
  open: "الفريق متاح خلال ساعات العمل.",
  session: "يرجى تسجيل الدخول مجدداً.",
  waiting: "جارٍ الاتصال بالدعم…",
  edited: "عُدّلت",
  searchFirst: "يرجى البحث في المساعدة أولاً.",
};
export function language(locale: string, brandLocale = "en") {
  const dictionaries: Record<string, typeof en> = { en, ar };
  const chain = [
    locale,
    locale.split("-")[0],
    brandLocale,
    brandLocale.split("-")[0],
    "en",
  ];
  const chosen = chain.find((x) => dictionaries[x])!;
  return {
    strings: dictionaries[chosen],
    locale: chosen,
    dir: /^(ar|fa|he|ur)(-|$)/.test(locale) ? "rtl" : "ltr",
  };
}
