"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,CheckCheck,ChevronRight,MessageSquare,Send,X} from 'lucide-react';
import {api,defaults,type Settings,type Message,timeOf} from './shared';
type Session={id:string;token:string};
export default function Messenger({embedded=false}:{embedded?:boolean}){
 const [session,setSession]=useState<Session|null>(null);const[settings,setSettings]=useState<Settings>(defaults);const[messages,setMessages]=useState<Message[]>([]);const[status,setStatus]=useState('open');const[view,setView]=useState('home');const[opened,setOpened]=useState(true);const[name,setName]=useState('');const[email,setEmail]=useState('');const[text,setText]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const scroll=useRef<HTMLDivElement>(null);const pending=useRef<{id:string;token:string;text:string}|null>(null);
 useEffect(()=>{api<{settings:Settings}>('/api/visitor?config=1').then(r=>setSettings(r.settings)).catch(e=>setError(e.message));try{const s=JSON.parse(localStorage.getItem('relay-visitor-session')||'null');if(s?.id&&s?.token)setSession(s);}catch{}},[]);
 useEffect(()=>{if(!session)return;let active=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const r=await api<{settings:Settings;messages:Message[];conversation:{status:string}}>('/api/visitor',undefined,{'x-conversation-id':session!.id,authorization:'Bearer '+session!.token});if(active){setSettings(r.settings);setMessages(r.messages);setStatus(r.conversation.status);setError('');}}catch(e){if(active)setError((e as Error).message);}finally{if(active)timer=setTimeout(poll,2000);}}void poll();return()=>{active=false;clearTimeout(timer)};},[session]);
 useEffect(()=>{const el=scroll.current;if(el&&el.scrollHeight-el.scrollTop-el.clientHeight<200)el.scrollTop=el.scrollHeight;},[messages]);
 async function send(){if(busy||!text.trim())return;setBusy(true);setError('');if(!pending.current||pending.current.text!==text)pending.current={id:crypto.randomUUID(),token:crypto.randomUUID()+crypto.randomUUID(),text};const p=pending.current;try{if(!session){const r=await api<{id:string}>('/api/visitor',{action:'start',name,email,text,messageId:p.id,token:p.token});const s={id:r.id,token:p.token};localStorage.setItem('relay-visitor-session',JSON.stringify(s));setSession(s);}else{await api('/api/visitor',{action:'send',text,messageId:p.id},{'x-conversation-id':session.id,authorization:'Bearer '+session.token});setMessages(v=>[...v.filter(x=>x.id!==p.id),{id:p.id,kind:'visitor',body:text,sender:name||'You',created_at:Date.now()}]);}setText('');pending.current=null;setView('chat');setStatus('open');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const panel=<section className="messenger-card" aria-label="Customer messenger" style={{'--messenger-accent':settings.color} as React.CSSProperties}><header className={`messenger-head ${view==='home'?'home-head':''}`}><div className="messenger-brand"><MessageSquare size={22}/><b>{settings.brand}</b>{!embedded&&<button aria-label="Close messenger" className="icon-btn" onClick={()=>setOpened(false)}><X size={18}/></button>}</div>{view==='home'?<><div className="support-avatars"><span>R</span><span>S</span><span>J</span></div><h1>{settings.greeting}</h1><p>{settings.availability}</p></>:<div className="chat-head-row"><button className="icon-btn" aria-label="Back to messenger home" onClick={()=>setView('home')}><ArrowLeft size={19}/></button><div><b>{settings.brand} support</b><p>{settings.availability}</p></div></div>}</header>
 {view==='home'?<div className="messenger-home"><button className="start-chat" onClick={()=>setView('chat')}><span><b>{session?'Continue your conversation':'Send us a message'}</b><small>We’re here to help.</small></span><Send size={19}/></button>{session&&messages.length>0&&<div className="recent-conversation"><h3>Your conversation</h3><button onClick={()=>setView('chat')}><span><b>{messages.at(-1)?.kind==='visitor'?'You':settings.brand}</b><small>{messages.at(-1)?.body}</small></span><ChevronRight size={16}/></button></div>}<div className="messenger-home-note"><MessageSquare size={27}/><p>A real person. A helpful answer.</p></div>{error&&<p role="alert" className="inline-error">{error}</p>}</div>:<><div className="visitor-thread" ref={scroll} aria-live="polite">{!session?<div className="intro-form"><h2>Let’s start a conversation</h2><p>Tell us a little about yourself so we can help.</p><label>Your name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} autoComplete="name" placeholder="Alex Morgan"/></label><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" maxLength={150} autoComplete="email" placeholder="alex@example.com"/></label></div>:<><div className="visitor-start">{settings.brand} support</div>{messages.map(m=><div key={m.id} className={`visitor-message ${m.kind==='visitor'?'outgoing':''}`}><div className="visitor-bubble">{m.body}</div><small>{m.kind==='agent'?settings.brand:'You'} · {timeOf(m.created_at)}{m.kind==='visitor'&&<CheckCheck size={11}/>}</small></div>)}{status==='closed'&&<p className="resolved-message">Conversation resolved. Send a message to reopen it.</p>}</>}</div>{error&&<p role="alert" className="inline-error">{error}</p>}<form className="visitor-composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea aria-label="Your message" value={text} onChange={e=>setText(e.target.value)} placeholder="Write your message…" maxLength={5000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button aria-label="Send message" disabled={busy||!text.trim()||(!session&&(!name.trim()||!email.trim()))}><Send size={18}/></button></form></>}
 <footer className="messenger-footer"><MessageSquare size={12}/>Powered by <b>Relay</b></footer></section>;
 if(embedded)return <div className="embedded-messenger">{panel}</div>;
 return <main className="messenger-demo"><header><a href="/" className="demo-logo"><span className="brand-mark"><MessageSquare size={19}/></span>Relay</a><a href="/" className="secondary-btn">Open team inbox<ArrowUpRight size={14}/></a></header><div className="demo-copy"><span className="eyebrow">CUSTOMER PREVIEW</span><h1>Every conversation<br/>starts with hello.</h1><p>Meet your messenger. Send a message here,<br/>then reply from your team inbox.</p><div className="preview-private"><span/>Private workspace preview</div></div>{opened&&panel}<button aria-label={opened?'Close messenger':'Open messenger'} className="messenger-launcher" style={{background:settings.color}} onClick={()=>setOpened(!opened)}>{opened?<X size={25}/>:<MessageSquare size={25}/>}</button></main>
}
