import {env} from 'cloudflare:workers';
import {legacyWritesEnabled} from '@/server/agent-bridge';
import {z} from 'zod';
import {ApiError,body,database,failure,hash,publicSettings,response,sameOrigin,type Workspace} from '@/lib/relay-server';
export const dynamic='force-dynamic';
async function session(request:Request){const id=request.headers.get('x-conversation-id');const token=request.headers.get('authorization')?.replace(/^Bearer /,'');if(!id||!token||token.length>150)throw new ApiError('Please start a conversation.',401);const c=await database().prepare('SELECT id,name,status FROM conversations WHERE id=? AND token_hash=? AND sample=0').bind(id,await hash(token)).first<{id:string;name:string;status:string}>();if(!c)throw new ApiError('This conversation is unavailable.',401);return c;}
async function settings(){const w=await database().prepare('SELECT * FROM workspace WHERE id=?').bind('main').first<Workspace>();if(!w)throw new ApiError('The messenger is getting ready. Open the inbox first.',503);return publicSettings(w);}
export async function GET(request:Request){try{const config=await settings();if(new URL(request.url).searchParams.has('config'))return response({settings:config});const c=await session(request);const {results}=await database().prepare("SELECT id,kind,body,sender,created_at FROM messages WHERE conversation_id=? AND kind='agent' OR conversation_id=? AND kind='visitor' ORDER BY created_at,id").bind(c.id,c.id).all();return response({settings:config,conversation:c,messages:results});}catch(e){return failure(e);}}
const schema=z.discriminatedUnion('action',[
z.object({action:z.literal('start'),name:z.string().trim().min(1).max(80),email:z.string().trim().email().max(150),text:z.string().trim().min(1).max(5000),messageId:z.string().uuid(),token:z.string().min(64).max(100)}),
z.object({action:z.literal('send'),messageId:z.string().uuid(),text:z.string().trim().min(1).max(5000)})]);
export async function POST(request:Request){try{sameOrigin(request);if(!legacyWritesEnabled(env))throw new ApiError("Legacy chat writes are disabled after storage cutover.",409);await settings();const parsed=schema.safeParse(await body(request));if(!parsed.success)throw new ApiError('Enter your name, a valid email, and a message of up to 5,000 characters.');const p=parsed.data;const db=database();const now=Date.now();if(p.action==='start'){
const id='chat-'+p.messageId;const tokenHash=await hash(p.token);const exists=await db.prepare('SELECT token_hash FROM conversations WHERE id=?').bind(id).first<{token_hash:string}>();if(exists&&exists.token_hash!==tokenHash)throw new ApiError('Unable to start this conversation.',409);
await db.batch([db.prepare('INSERT OR IGNORE INTO conversations (id,token_hash,name,email,title,status,assigned,priority,unread,sample,tag,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,tokenHash,p.name,p.email,p.text.slice(0,70),'open','',0,1,0,'New conversation',now,now),db.prepare('INSERT OR IGNORE INTO messages (id,conversation_id,kind,body,sender,created_at) VALUES (?,?,?,?,?,?)').bind(p.messageId,id,'visitor',p.text,p.name,now)]);return response({id},201);}
const c=await session(request);const existing=await db.prepare('SELECT id,conversation_id FROM messages WHERE id=?').bind(p.messageId).first<{id:string;conversation_id:string}>();if(existing){if(existing.conversation_id!==c.id)throw new ApiError('Message not accepted.',409);return response({ok:true});}
await db.batch([db.prepare('INSERT OR IGNORE INTO messages (id,conversation_id,kind,body,sender,created_at) VALUES (?,?,?,?,?,?)').bind(p.messageId,c.id,'visitor',p.text,c.name,now),db.prepare("UPDATE conversations SET status='open',unread=1,updated_at=? WHERE id=?").bind(now,c.id)]);return response({ok:true});}catch(e){return failure(e);}}
